### ISSUE TITLE
Google translate

### ISSUE THREAD

**Issue by keighrim** [keighrim/bananaCoRR#1]
##### Documentation

https://cloud.google.com/translate/v2/using_rest
##### Python wrapper

https://developers.google.com/api-client-library/python/apis/translate/v2
##### APIs

https://developers.google.com/resources/api-libraries/documentation/translate/v2/python/latest/

The problem I just found is that google translate API is a **paid service**.
But, google gives away $300 to a first time guest and we need only $20 for querying 1 M words to google translate.

We can try that, otherwise we can find a kind of more like a dictionary services rather than translation
(from EN -> FR, GE, RU)

**Comment by ceparadise** [comment]
I think maybe we can use Moses to do the translation or other application

http://www.statmt.org/moses/?n=Public.Demos
http://en.wikipedia.org/wiki/Comparison_of_machine_translation_applications

right now I am trying to figure how to use it.

**Comment by ceparadise** [comment]
I found the Moese on our department system. Path:/home/j/clp/chinese/tools/mosesdecoder
I am thinking about how to run it. Do you guys have any experience before?

**Comment by keighrim** [comment]
Unfortunately I have no experience, in fact I've never heard of it before..
Could you try?

How about you Todd?

**Comment by tcurcuru** [comment]
I have a lot of experience with Moses from the Bible, but I have no experience with the translation software.
